### PR TITLE
Depend on semigroups for <>

### PR DESCRIPTION
**Pull request by phadej**
aeson already depends on semigroups (same conditional)

### CODE REVIEW

**Comment by informatikr** [comment]
Is there a reason for the change besides being slightly more precise?

**Comment by phadej** [comment]
```
% cabal new-build -w ghc-8.2.2 --constraint=base-compat==0.10.0
Resolving dependencies...
Build profile: -w ghc-8.2.2 -O1
In order, the following will be built (use -v for more details):
 - aeson-pretty-0.8.5 (lib) (configuration changed)
 - aeson-pretty-0.8.5 (exe:aeson-pretty) (configuration changed)
Configuring library for aeson-pretty-0.8.5..
Preprocessing library for aeson-pretty-0.8.5..
Building library for aeson-pretty-0.8.5..
[1 of 1] Compiling Data.Aeson.Encode.Pretty ( Data/Aeson/Encode/Pretty.hs, /home/ogre/Documents/other-haskell/aeson-pretty/dist-newstyle/build/x86_64-linux/ghc-8.2.2/aeson-pretty-0.8.5/build/Data/Aeson/Encode/Pretty.o )

Data/Aeson/Encode/Pretty.hs:152:67: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at Data/Aeson/Encode/Pretty.hs:64:21-24
                          or ‘Prelude.Compat.<>’,
                             imported from ‘Prelude.Compat’ at Data/Aeson/Encode/Pretty.hs:73:1-21
                             (and originally defined in ‘Data.Semigroup’)
    |
152 | encodePrettyToTextBuilder' Config{..} x = fromValue st (toJSON x) <> trail
```

**Comment by phadej** [comment]
I went ahead and made CI use `packcheck` https://github.com/harendra-kumar/packcheck, testing only with `stack` (with fixed `stack.yaml` files) makes testing bound relaxation very cumbersome (one have to add correct `extra-deps` which is busywork, there's solver!)

currently `base-compat` doesn't work with GHC-8.2.2 and GHC-8.0.2

```
                     8.4.1  8.2.2  8.0.2  7.10.3  7.8.4  7.6.3  7.4.2  7.2.2  7.0.4
aeson-pretty-0.8.6/  OK     FAIL   FAIL   OK      OK     OK     OK     NO-IP  NO-IP
aeson-pretty-0.8.5/  OK     OK     OK     OK      OK     OK     OK     NO-IP  NO-IP
aeson-pretty-0.8.4/  OK     OK     OK     OK      OK     DEP    OK     NO-IP  NO-IP
```

**Comment by phadej** [comment]
I made a revision for 0.8.6

```diff
diff --git a/aeson-pretty.cabal b/aeson-pretty.cabal
index 72aa856..1686a6c 100644
--- a/aeson-pretty.cabal
+++ b/aeson-pretty.cabal
@@ -36,6 +36,10 @@ flag lib-only
     default: False
 
 library
+    -- broken with base-compat-0.10, <> ambiguous: Prelude.Compat and Data.Monoid
+    build-depends:
+      base >= 4.11 || < 4.9
+
```

so now matrix is green

```
                     8.4.1  8.2.2  8.0.2  7.10.3  7.8.4  7.6.3  7.4.2  7.2.2  7.0.4
aeson-pretty-0.8.6/  OK     NO-IP  NO-IP  OK      OK     OK     OK     NO-IP  NO-IP
aeson-pretty-0.8.5/  OK     OK     OK     OK      OK     OK     OK     NO-IP  NO-IP
aeson-pretty-0.8.4/  OK     OK     OK     OK      OK     OK     OK     NO-IP  NO-IP
```

**Comment by phadej** [comment]
Let's make a solid CI, so this kind of mistakes won't happen in the future.

It's my bad I didn't test locally before making the PR (the only excuse: I did it via GitHub, as it's handy).

**Comment by informatikr** [comment]
Thanks, it's in the newest version on Hackage. I appreciate that you fixed Travis build!
